const PRIVATE_HOST_RE=/^(localhost|127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/i;
function decodeHtml(s=''){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
const bad=/logo|icon|avatar|sprite|banner|header|footer|social|facebook|instagram|twitter|x\.com|paypal|spinner|loading|placeholder|tracking|pixel|advert|cookie/i;
const good=/poster|print|artwork|art-|product|gallery|large|full|main|hero|image|img|media/i;
function attrs(s){const o={};for(const m of s.matchAll(/([\w:-]+)\s*=\s*["']([^"']*)["']/g))o[m[1].toLowerCase()]=decodeHtml(m[2]);return o}
function titleWords(s=''){return s.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>3).slice(0,8)}
function candidates(html,pageUrl,title=''){
  const out=[];const words=titleWords(title);
  const add=(url,score,alt='',w=0,h=0)=>{if(!url)return;try{url=new URL(decodeHtml(url),pageUrl).href}catch{return}const hay=`${url} ${alt}`;if(bad.test(hay))score-=180;if(good.test(hay))score+=35;for(const word of words)if(hay.toLowerCase().includes(word))score+=12;if(w&&h){const area=w*h;if(area>120000)score+=35;else if(area>40000)score+=18;if(h>w*1.1)score+=8}out.push({url,score})};
  for(const m of html.matchAll(/<meta[^>]+>/gi)){const a=attrs(m[0]),k=(a.property||a.name||a.itemprop||'').toLowerCase();if(k==='og:image'||k==='og:image:url')add(a.content,140);else if(k==='twitter:image'||k==='twitter:image:src')add(a.content,125);else if(k==='image')add(a.content,95)}
  for(const m of html.matchAll(/<link[^>]+>/gi)){const a=attrs(m[0]);if((a.rel||'').toLowerCase().includes('image_src'))add(a.href,100)}
  for(const m of html.matchAll(/<img[^>]*>/gi)){const a=attrs(m[0]),src=a['data-src']||a['data-lazy-src']||a.src||((a.srcset||'').split(',').pop()||'').trim().split(/\s+/)[0],w=Number(a.width)||0,h=Number(a.height)||0;add(src,20,a.alt||a.title||'',w,h)}
  return out.sort((a,b)=>b.score-a.score);
}
export default async function handler(req,res){try{const raw=Array.isArray(req.query.url)?req.query.url[0]:req.query.url,title=Array.isArray(req.query.title)?req.query.title[0]:(req.query.title||'');if(!raw)return res.status(400).send('Missing url');const u=new URL(raw);if(!/^https?:$/.test(u.protocol)||PRIVATE_HOST_RE.test(u.hostname))return res.status(400).send('Invalid url');const page=await fetch(u,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; CollectionReferenceBot/2.0)'}});if(!page.ok)return res.status(404).send('Source unavailable');const ct=page.headers.get('content-type')||'';let imageUrl='';if(ct.startsWith('image/'))imageUrl=page.url;else{const html=(await page.text()).slice(0,1800000),ranked=candidates(html,page.url,title);if(!ranked.length||ranked[0].score<35)return res.status(404).send('No trustworthy reference image found');imageUrl=ranked[0].url}const iu=new URL(imageUrl);if(!/^https?:$/.test(iu.protocol)||PRIVATE_HOST_RE.test(iu.hostname))return res.status(400).send('Invalid image url');const ir=await fetch(iu,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0','referer':page.url}});if(!ir.ok)return res.status(404).send('Image unavailable');const ict=ir.headers.get('content-type')||'image/jpeg';if(!ict.startsWith('image/'))return res.status(415).send('Not an image');const buf=Buffer.from(await ir.arrayBuffer());if(buf.length>8*1024*1024)return res.status(413).send('Image too large');res.setHeader('Content-Type',ict);res.setHeader('Cache-Control','public, max-age=86400, s-maxage=604800, stale-while-revalidate=2592000');res.status(200).send(buf)}catch(e){res.status(500).send('Reference image unavailable')}}
